export const randomSentences = [
  'Os seus segredos estão seguros comigo, juro!',
  'aqui é onde grandes ideias e listas de compras se encontram.',
  'prometo não contar às outras notas se você me escrever algo interessante.',
  'digite rápido, pense devagar - ou não, você decide!',
  'aqui, as palavras têm o poder de mudar o mundo... ou pelo menos o seu dia.',
  'suas ideias têm espaço para dançar, mesmo que seja só na linha de um texto.',
  'que tal escrever o próximo grande espetáculo da broadway?',
  'não vá se esquecer do que estava para anotar hein!?',
  'O elefante é o único animal que não pode pular.',
  `a granada é chamada assim por sua semelhança com uma romã, já que "granatum" em latim significa "repleto de grãos".`,
  'O criador da lâmpada elétrica, Thomas Edison, tinha medo do escuro.',
  'Os seres humanos e as girafas têm o mesmo número de vértebras no pescoço: sete.',
  'Um caracol pode dormir por até três anos.',
  'Brasil é o maior produtor mundial de laranjas.',
  `Um grupo de girafas é chamado de "torre".`,
  'As formigas dormem apenas cerca de 4 minutos por dia.',
  'O algodão-doce foi inventado por um dentista.',
  'Em média, uma pessoa passa cerca de 20 anos de sua vida dormindo.',
  'As formigas esticam ao acordar pela manhã. Isso também é conhecido como pandiculação!',
  'Júpiter é tão massivo que poderia conter todos os outros planetas do Sistema Solar dentro de si.',
  'Uma colher de chá de uma estrela de nêutrons pesaria milhões de toneladas na Terra.',
  'Se pudéssemos desenrolar todos os anéis de Saturno, eles formariam uma faixa com cerca de 400.000 quilômetros de comprimento.',
  'A estrela mais próxima da Terra, Proxima Centauri, faz parte do sistema Alpha Centauri, mas é uma estrela solitária.',
  'A luz do Sol leva cerca de 8 minutos e 20 segundos para chegar à Terra.',
  'Plutão não era considerado um planeta anão quando foi descoberto em 1930, mas foi reclassificado em 2006.',
  'A Grande Mancha Vermelha em Júpiter é uma tempestade que dura há pelo menos 350 anos.',
  'Uma maçã a uma distância de 1 metro da Terra sente a atração gravitacional da Terra.',
  'A estrela mais distante visível a olho nu da Terra é V762 Cassiopeiae, a cerca de 16.308 anos-luz de distância.'
]
